language: ruby
rvm:
- 2.3.3

script: bash ./deploy.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - travis-build     # build website on this branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
