# Gems
plugins:
  - octopress-paginate
  - jekyll-gist

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Diego Versiani
tagline:          'Passionate Web Developer'
description:      'I make<br>Fast WordPress Websites<br>for any screen size.'
url:              https://diegoversiani.me
baseurl:          /

author:
  name:           'Diego Versiani'
  email:           diegoversiani@gmail.com

pagination:
  limit:          false
  per_page:       10
  title_suffix:   " (page :num)"

# Custom vars
version:          2.1.0

gravatar_url:     https://www.gravatar.com/avatar/09bde1935a1a7c56c7f6529fdc148956?size=100

github:
  repo:           https://github.com/diegoversiani
