# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
sass:
  style: :compressed

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dvlopes.github.io" # the base hostname & protocol for your site
title: dvlopes
description: >
  Full Stack Developer - WordPress Themes Developer
copyright: Feel free to use what you find in this website, unless noted.

# Owner's Info
show_email_on_footer: true
show_phone_on_footer: true
email: diegoversiani@gmail.com
phone: +55 31 99350-6848
owner_profile_img_url: http://www.gravatar.com/avatar/09bde1935a1a7c56c7f6529fdc148956?size=250
owner_name: Diego Versiani
owner_title: Full Stack Developer - WordPress Themes Developer
about_me: >
  About me!

# Social Networks properties
show_social_networks: true
facebook_username: diego.versiani.pires.lopes
github_username: dvlopes
twitter_username: diegoversiani
wordpress_username: diegoversiani

# Includes
include_fontawesome: true
