# Gems
gems:
  - octopress-paginate
  - jekyll-gist
  - pygments.rb

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Diego Versiani
tagline:          'Passionate Web Developer'
description:      'I develop Responsive WordPress websites for meaningful user experiences.'
url:              http://diegoversiani.me
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

pagination:
  limit:          false
  per_page:       10
  title_suffix:   " (page :num)"

# Custom vars
version:          2.1.0

gravatar_url:     https://www.gravatar.com/avatar/09bde1935a1a7c56c7f6529fdc148956?size=100

github:
  repo:           https://github.com/diegoversiani
