# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
sass:
  style: :compressed

# Site settings
title: dvlopes
email: diegoversiani@gmail.com
description: >
  Full Stack Developer - WordPress Themes Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dvlopes.github.io" # the base hostname & protocol for your site

# Social Networks properties
facebook_username: diego.versiani.pires.lopes
github_username: dvlopes
twitter_username: 
