# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: ['bower_components','node_modules','bower.json','package.json','gulpfile.js','README.md']

gems:
  - jekyll-sitemap

# Site settings
title: Diego Versiani
subtitle: Web Developer & UX Designer
description: >
  I develop WordPress Websites for meaningful user experiences. 
  About me: I love to create stuff, it can be websites, houses, the interior of my motorhome 
  or delicious meals. I like traveling, baking and fermenting food in jars.
baseurl: "" # the subpath of your site, e.g. /blog 
url: "http://diegoversiani.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown